<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE CDlist[
    <!ELEMENT CDlist ((CD)+)>
    <!ELEMENT CD (composer, (performance)+, publisher, (length)?)>
    <!ELEMENT performance (composition, (soloist)?,(orchestra, conductor)?)>
    <!ELEMENT composer (#PCDATA)>
    <!ELEMENT publisher (#PCDATA)>
    <!ELEMENT length (#PCDATA)>
    <!ELEMENT composition (#PCDATA)>
    <!ELEMENT soloist (#PCDATA)>
    <!ELEMENT orchestra (#PCDATA)>
    <!ELEMENT conductor (#PCDATA)>
]>
<CDlist>
    <CD>
        <composer>Johannes Brahms</composer>
        <performance>
            <composition>Piano Concerto No. 2</composition>
            <soloist>Emil Gilels</soloist>
            <orchestra>Berlin Philharmonic</orchestra>
            <conductor>Eugen Jochum</conductor>
        </performance>
        <performance>
            <composition>Piano Concerto No. 2</composition>
            <orchestra>Berlin Philharmonic</orchestra>
            <conductor>Eugen Jochum</conductor>
        </performance>
        <performance>
            <composition>Fantasias Op. 116</composition>
            <soloist>Emil Gilels</soloist>
        </performance>
        <publisher>Deutsche Grammophon</publisher>
        <!--length is expressed in ISO standard duration format: 1h 13' 37'' -->
        <length>PT1H13M37S</length>
    </CD>
    <CD>
        <composer>Johannes Brahms</composer>
        <performance>
            <composition>Piano Concerto No. 2</composition>
            <soloist>Emil Gilels</soloist>
            <orchestra>Berlin Philharmonic</orchestra>
            <conductor>Eugen Jochum</conductor>
        </performance>
        <performance>
            <composition>Piano Concerto No. 2</composition>
            <orchestra>Berlin Philharmonic</orchestra>
            <conductor>Eugen Jochum</conductor>
        </performance>
        <performance>
            <composition>Piano Concerto No. 2</composition>
            <soloist>Emil Gilels</soloist>
            <orchestra>London Symphony Orchestra</orchestra>
            <conductor>Eugen Jochum</conductor>
        </performance>
        <performance>
            <composition>Fantasias Op. 116</composition>
            <soloist>Emil Gilels</soloist>
        </performance>
        <publisher>Deutsche Grammophon</publisher>
        <!--length is expressed in ISO standard duration format: 1h 13' 37'' -->
        <length>PT1H13M37S</length>
    </CD>
</CDlist>
